version: "3"
services:
  proxy:
    container_name: hans-proxy
    image: nginx:1.23.3-alpine
    ports:
      - 80:80
    depends_on:
      - business
    volumes:
      - ./loadbalance/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    networks:
      - hans
  business:
    image: eddielin0926/hans-business
    build: ./business
    environment:
      PORT: 8100
      INVENTORY_URL: ${INVENTORY_URL}
      STORAGE_URL: ${STORAGE_URL}
    ports:
      - 8100:8100
    depends_on:
      - inventory
      - storage
    networks:
      - hans
  inventory:
    image: eddielin0926/hans-inventory
    build: ./inventory
    environment:
      PORT: 8200
    networks:
      - hans
  storage:
    image: eddielin0926/hans-storage
    build: ./storage
    environment:
      PORT: 8300
    networks:
      - hans
  
networks:
  hans:
    driver: bridge
