version: "3"
services:
  business:
    image: eddielin0926/hans-business
    build: ./business
    environment:
      PORT: 8100
      INVENTORY_URL: ${INVENTORY_URL}
      STORAGE_URL: ${STORAGE_URL}
    ports:
      - 8100:8100
    depends_on:
      - inventory
      - storage
    networks:
      - hans
  inventory:
    image: eddielin0926/hans-inventory
    build: ./inventory
    environment:
      PORT: 8200
    networks:
      - hans
  storage:
    image: eddielin0926/hans-storage
    build: ./storage
    environment:
      PORT: 8300
    networks:
      - hans
  
networks:
  hans:
    driver: bridge
