version: "3"
services:
  proxy:
    container_name: hans-proxy
    image: nginx:1.23.3-alpine
    ports:
      - 80:80
    depends_on:
      - business1
      - business2
    volumes:
      - ./loadbalance/nginx.conf:/etc/nginx/nginx.conf
    restart: always

  business1:
    image: eddielin0926/hans-business
    build: ./business
    restart: always
    environment:
      PORT: 8100
      INVENTORY_URL: ${INVENTORY_URL}
      STORAGE_URL: ${STORAGE_URL}
    ports:
      - 8100:8100

  business2:
    image: eddielin0926/hans-business
    build: ./business
    environment:
      PORT: 8100
      INVENTORY_URL: ${INVENTORY_URL}
      STORAGE_URL: ${STORAGE_URL}
    ports:
      - 8100:8100

  inventory:
    image: eddielin0926/hans-inventory
    build: ./inventory
    restart: always
    environment:
      PORT: 8200

  storage:
    image: eddielin0926/hans-storage
    build: ./storage
    restart: always
    environment:
      PORT: 8300:8300
